### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by evhumphrey** [sirivatd/trade-blitz#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* I like the `check out my other stuff link` 👍
* Great job on the proposal! Most of the feedback is around your schema; I think it can be simplified

---

# MVP List

- [ ] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments

* Right now there are 8MVPs, which seems doable given the time estimate given. I recommend having the News mvp as a bonus feature.
* Each of the MVPs (where it makes sense) should have the following bullet points: Adequate styling | Smooth, bug-free navigation | Adequate and appropriate seeds to demonstrate the feature
* The Account MVP mentions having a watchlist; I would add a Watchlist MVP (maybe after the search mvp)
---

# Database Schema

- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

* `accounts` table
  * I would rename the `percent_gain` to `percent_change`
  * What does the `experience` store?
  * You may not need this table; you can calculate a lot of information based on a user's orders
* `orders` table
  * You should index `account_id` and `stock_id`
  * You should add a `purchase_date` and `purchase_price`
* `user_orders`
  * You might not need this table. You can calculate most of this stuff by looking at orders for a user
* A `watchlists` table will be necessary for watchlists to work
* `atheletes`
  * It looks like you are designing this for basketball. Note that if you wanted (at a later time) to allow different sports, you might want to consider having  `atheletes_info` and `athletes_stats` tables to allow for more flexibility. Not needed at this point, but something to think about
* `stocks`
  * Won't need a quantity (`orders` will store this), and may not need `symbol` (you could leave it in this table, or use the one in the `atheletes` table, but only keep one so you're not duplicating information)

---

# Sample State

- [x] State shape is flat!
- [ ] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

* While snake_case on the backend, you’ll want the json returned to have camelCase keys. This is a pretty cool resource on this: APIs supporting snake_case and camelCase with Rails

---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* Your `stocks` endpoints may change a little bit with the schema changes mentioned above

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by sirivatd** [comment]
Made necessary changes
